### PR TITLE
Wrap input example in a ScrollView to prevent text from being cut off

### LINKED ISSUE #769: Input example output text is cut off on some devices
Restructure the example or wrap the items in a scroll view to prevent text from being cut off.

f2b9054e-f413-4430-8f24-d0793015f826

### PR DESCRIPTION
**Pull request by cookieguru**
Fixes #769, refactor the input example:
* Put all elements inside a ScrollView in order to prevent the text from being cut off
* Add a number input
* Update the text to demonstrate getters for each input type

Examples are for demonstrating application features and not for boilerplate code, but I would like to see input filtering to the number input as soon as #537 is fixed (the curren behavior causes the entry to appear in reverse order on Android).

### CODE REVIEW

**Comment by mpost** [comment]
Thanks for the contribution... Putting the content into a `ScrollView` makes sense.

**Comment by mpost** [comment]
With the introduction of the "new" operator in Tabris 1.7 your PR will not merge easily. Would you be willing to update it?

**Comment by cookieguru** [comment]
@mpost Indeed that did not merge well.  I've replaced all the `tabris.create` calls with `new` operators so this should merge much easier now.

**Comment by mpost** [comment]
@cookieguru Thanks

**Comment by gosia-eclipsesource** [comment]
Sorry for taking so long before merging this PR. It's now included for 1.9, thanks @cookieguru!

**Pull request closed without merging**
