### PR TITLE
Update examples to set properties directly

### PR DESCRIPTION
**Pull request by cookieguru**
- [X] Code is up-to-date with current `master`
- [X] Code is provided under the terms of the [Tabris.js license](https://github.com/EclipseSource/tabris-js/blob/master/LICENSE)

With 2.x, properties are encouraged to be set directly rather than with getters/setters.  This PR updates snippets and examples that used the `set` method for a single property at a time.  There are some files that still utilize the `set` method that have not been changed as these occurrences call `set` with an object to set multiple properties at once.

### CODE REVIEW

**Comment by mpost** [comment]
Thanks for the PR. Your proposed changes will however not work since `find()` returns a collection of widgets on which you would have to call `first()` to get the only found widget.

**Comment by cookieguru** [comment]
1. Write
2. PR
3. Test
😳

**Comment by mpost** [comment]
Thanks for your efforts though. The syntax you implied in the changes would be handy but it is not so easy to provide consistently.

**Comment by cookieguru** [comment]
The `first()` method is handy though, I will keep it in mind.  In my code I have been using `[0]` to avoid the overhead of calling a function.

**Pull request closed without merging**
