### PR TITLE
Add documentation for debuggers

### PR DESCRIPTION
**Pull request by cookieguru**
As pointed out in #1149, the current documentation for debugging is just a link to the Android/Eclipse blog post.  Unless a user specifically went looking for blog posts, they would not know it's possible to debug Tabris.js apps through Chrome Developer Tools.  It would be nice to centralize all the debugging information in a single page in the documentation rather than having to search for various blog posts.  This PR creates a new page with a brief overview of debuggers and information about the Android debuggers.  Since there is no existing documentation on using Xcode nor Visual Studio (nor have I used them myself) I can't comment on the setup procedures to either of those so they will have to be added in future commits.

### CODE REVIEW

**Comment by mpost** [comment]
Thanks for the documentation. One comment on the Android requirements: when using the chrome based debugging facilities you do not need the android tools/adb installed.

**Comment by camstuart** [comment]
Nice one @cookieguru looking forward to giving this a try

**Comment by ralfstx** [comment]
@cookieguru Looks good. Good you please rebase your change to current master to get rid of the build failure?
@mpost Do you request a change or would you add your comments to the doc after it's merged?

**Comment by mpost** [comment]
@ralfstx This should be adjusted since the chrome dev tools are most likely the more popular debugging solution and you don't need any Android tooling for it.

**Comment by cookieguru** [comment]
@mpost @ralfstx Updated the text to reflect that ADB isn't required for Chrome debugging.

**Comment by ralfstx** [comment]
@cookieguru Thanks for the update. Unfortunately, I can't submit your change because of the build problem fixed with d0541dc and b861c27. Could you please rebase to current master?

**Comment by cookieguru** [comment]
@ralfstx I had issues with Git; will retry this as #1175.

**Pull request closed without merging**
