### PR TITLE
Add Switch to input example

### PR DESCRIPTION
**Pull request by cookieguru**

### CODE REVIEW

**Comment by gosia-eclipsesource** [comment]
:+1: for "Book with miles". @mpost I would think of "Collect miles" more as earning miles, not redeeming them on a flight.

**Comment by mpost** [comment]
@gosia-eclipsesource My impression was that a switch should indicate that we want to earn the miles. If we were to earn redeem miles, i would expect that to happen later in the booking process. But for a demo either way should work. I would than vote for "Redeem miles:" as it is shorter.

**Comment by cookieguru** [comment]
I actually had a hard time coming up with a suitable binary choice on this one ;) 

The switch is an important input element and should definitely be in a demo somewhere, and this seemed the most logical place to put it.  The label doesn't really matter since the switch doesn't do anything, but of course the label has to make sense in context with the others on the page.

I agree with Gosia's assessment and have changed the label to "Redeem miles".

**Comment by gosia-eclipsesource** [comment]
Merged via gerrit. Thanks @cookieguru

**Comment by gosia-eclipsesource** [comment]
P.S. @cookieguru Good luck with your SeattleJS submission :+1: :tada: Thanks so much and let us know if you need anything!

**Pull request closed without merging**
