### PR TITLE
Clarify Tab documentation to note that images are not shown for top tab bars

### PR DESCRIPTION
**Pull request by cookieguru**
As mentioned in #1001

### CODE REVIEW

**Comment by ralfstx** [comment]
Thanks for the PR! We're using Gerrit for code reviews internally and haven't yet sorted out how to automatically synchronize GitHub PRs with this workflow, so I have to do this manually.

Unfortunately, Gerrit has a complaint about your commit:

    remote: (W) 77b69c1: commit subject >65 characters; use shorter first paragraph
    remote: (W) 77b69c1: commit message lines >70 characters; manually wrap lines

Could you update the commit message, then I'll try again.

**Comment by cookieguru** [comment]
@ralfstx Fixed.  Is it possible to add a script like [this](http://stackoverflow.com/a/34664075/6771274) to Travis to fail the build if the commit message exceeds 65 characters?

**Comment by ralfstx** [comment]
Thanks for the pointer, @cookieguru! @mknauer Could you try to include this script in our Gerrit setup?

**Comment by ralfstx** [comment]
The change is included as 96e11942d20c58f615a12d42c07f691bdde27be3. I had to rebase it since our Gerrit strategy does not work with merge commits.

GitHub does not recognize the rebased commits as part of a PR, so the PR won't get marked as "merged" (and you cannot do that manually). This is unfortunate, we have to find a better solution for handling PRs.

**Pull request closed without merging**
